apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: LoadBalancer
  ports:
  - name: neo4j1
    port: 7474
  - name: neo4j2
    port: 7687
  selector:
    app: neo4j
  clusterIP: 10.97.190.74
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - image: neo4j:5.10.0
        name: neo4j
        env:
        - name: NEO4J_AUTH  
          value: "neo4j/neo4jTtk-"
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        ports:      
        - containerPort: 7687
          name: neo4j1
        - containerPort: 7474
          name: neo4j2
        volumeMounts:
        - name: neo4j-persistent-storage
          mountPath: /data
      volumes:
      - name: neo4j-persistent-storage
        persistentVolumeClaim:
          claimName: neo4j-pv-data
