apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: LoadBalancer
  ports:
  - port: 5432
  selector:
    app: postgresql
  clusterIP: 10.97.190.81
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:latest
        name: postgresql
        imagePullPolicy: Never
        env:
          # Use secret in prod use cases
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_USER
          value: test
        - name: POSTGRES_DB
          value: test
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pv-data
