apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - port: 9200
  selector:
    app: elasticsearch
  clusterIP: 10.97.190.72
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: permission-fix
        image: busybox:1.33.0
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /usr/share/elasticsearch/data
        command: [ 'chown' ]
        args: [ '1000:1000', '/usr/share/elasticsearch/data' ]
      containers:
      - image: elasticsearch:7.16.3
        name: elasticsearch
        imagePullPolicy: Never
        env:
        - name: 'discovery.type'
          value: 'single-node'
        ports:
        - containerPort: 9200
          name: elasticsearch
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pv-data
