apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  type: LoadBalancer
  ports:
  - port: 8983
  selector:
    app: solr
  clusterIP: 10.97.190.82
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: solr
spec:
  selector:
    matchLabels:
      app: solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - image: solr:9.4.0
        name: solr
        ports:
        - containerPort: 8983
          name: solr
        env:
        - name: SOLR_HEAP
          value: "512m" 
        - name: SOLR_HOST
          value: "solrcloud-1"
        - name: SOLR_HOST_PORT
          value: "8983"
        - name: ZK_HOST
          value: "zookeeper2:2182"     
        volumeMounts:
        - name: solr-data-persistent-storage
          mountPath: /var/solr
      volumes:
      - name: solr-data-persistent-storage
        persistentVolumeClaim:
          claimName: solr-pv-data
