apiVersion: v1
kind: Service
metadata:
  name: zookeeper2
spec:
  type: LoadBalancer
  ports:
  - port: 2182
  selector:
    app: zookeeper2
  clusterIP: 10.97.190.81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper2
spec:
  selector:
    matchLabels:
      app: zookeeper2
  template:
    metadata:
      labels:
        app: zookeeper2
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - image: confluentinc/cp-zookeeper:7.2.0
        name: zookeeper2
        ports:
        - containerPort: 2182
          name: zookeeper2
        env:
        - name: ZOOKEEPER_ID
          value: '2'  
        - name: ZOOKEEPER_CLIENT_PORT
          value: '2182'
        - name: ZOOKEEPER_TICK_TIME
          value: '2000'
        - name: ZOOKEEPER_SERVER_1
          value: 'zookeeper2'
        volumeMounts:
        - name: zookeeper-2-data-persistent-storage
          mountPath: /var/lib/zookeeper/data
        - name: zookeeper-2-log-persistent-storage
          mountPath: /var/lib/zookeeper/log
        - name: zookeeper-2-solr-persistent-storage
          mountPath: /etc/solr
      volumes:
      - name: zookeeper-2-data-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper-2-data-pv-data
      - name: zookeeper-2-log-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper-2-log-pv-data
      - name: zookeeper-2-solr-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper-2-solr-pv-data
