apiVersion: v1
kind: Service
metadata:
  name: dictionary
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: dictionary
  clusterIP: 10.97.190.90
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dictionary
spec:
  selector:
    matchLabels:
      app: dictionary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
      - image: dictionary:latest
        name: dictionary
        imagePullPolicy: Never
        env:
          # Use secret in prod use cases
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        ports:
        - containerPort: 8080
          name: dictionary