apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: LoadBalancer
  ports:
  - port: 9091
  selector:
    app: kafka
  clusterIP: 10.97.190.79
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
      - image: confluentinc/cp-kafka:7.2.0
        name: kafka
        env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper:2181'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'PLAINTEXT://localhost:9091,PLAINTEXT_HOST://localhost:39091'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'PLAINTEXT'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1' 
        ports:
        - containerPort: 9091
          name: kafka
        volumeMounts:
        - name: kafka-persistent-storage
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-persistent-storage
        persistentVolumeClaim:
          claimName: kafka-pv-data