apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: LoadBalancer
  ports:
  - port: 9092
  selector:
    app: kafka
  clusterIP: 10.97.190.79
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      enableServiceLinks: false
      hostname: kafka-con
      containers:
      - image: confluentinc/cp-kafka:7.2.0
        name: kafka
        env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper:2181'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'EXTERNAL_KUBERNETES://kafka:9092'
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'EXTERNAL_KUBERNETES:PLAINTEXT'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'EXTERNAL_KUBERNETES'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1' 
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: kafka-persistent-storage
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-persistent-storage
        persistentVolumeClaim:
          claimName: kafka-pv-data
