apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: LoadBalancer
  ports:
  - port: 2181
  selector:
    app: zookeeper
  clusterIP: 10.97.190.80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - image: confluentinc/cp-zookeeper:7.2.0
        name: zookeeper
        ports:
        - containerPort: 2181
          name: zookeeper
        env:
        - name: ZOOKEEPER_ID
          value: '1'  
        - name: ZOOKEEPER_CLIENT_PORT
          value: '2181'
        - name: ZOOKEEPER_TICK_TIME
          value: '2000'
        - name: ZOOKEEPER_SERVER_1
          value: 'zookeeper'
        volumeMounts:
        - name: zookeeper-data-persistent-storage
          mountPath: /var/lib/zookeeper/data
        - name: zookeeper-log-persistent-storage
          mountPath: /var/lib/zookeeper/log
        - name: zookeeper-kafka-persistent-storage
          mountPath: /etc/kafka
      volumes:
      - name: zookeeper-data-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper-data-pv-data
      - name: zookeeper-log-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper-log-pv-data
      - name: zookeeper-kafka-persistent-storage
        persistentVolumeClaim:
          claimName: zookeeper-kafka-pv-data
